apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: # kpt-merge: /free5gc-operator-controller-controller-controller-role
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: free5gc-operator-controller
    app.kubernetes.io/part-of: free5gc-operator-controller
    app.kubernetes.io/version: tbd
  name: free5gc-operator-controller-controller-controller-role
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRole|default|free5gc-operator-controller-controller-controller-role'
rules:
- apiGroups:
  - '*'
  resources:
  - events
  - configmaps
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - nf.nephio.org
  resources:
  - upfdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nf.nephio.org
  resources:
  - upfdeployments/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - free5gc.nephio.org
  resources:
  - imageconfigs
  - imageconfigs/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
