apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: # kpt-merge: /free5gc-operator-controller-controller-controller-role-binding
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: free5gc-operator-controller
    app.kubernetes.io/part-of: free5gc-operator-controller
    app.kubernetes.io/version: tbd
  name: free5gc-operator-controller-controller-controller-role-binding
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRoleBinding|default|free5gc-operator-controller-controller-controller-role-binding'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: free5gc-operator-controller-controller-controller-role
subjects:
- kind: ServiceAccount
  name: free5gc-operator-controller-controller
  namespace: free5gc
