apiVersion: ipam.nephio.org/v1alpha1
kind: IPAllocation
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
  creationTimestamp: null
  labels:
    nephio.org/interface: internet
  name: upf-edge2-internet
  namespace: upf
spec:
  kind: pool
  prefixLength: 16
  selector:
    matchLabels:
      nephio.org/network-instance: sample-vpc
status: {conditionedstatus: {conditions: []}, allocatedprefix: 10.2.0.0/16, gateway: ""}
