apiVersion: ipam.nephio.org/v1alpha1
kind: IPAllocation
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
  creationTimestamp: null
  labels:
    nephio.org/interface: n3
  name: upf-edge2-n3
  namespace: upf
spec:
  kind: network
  selector:
    matchLabels:
      nephio.org/network-instance: sample-vpc
      nephio.org/network-name: sample-n3-net
status: {conditionedstatus: {conditions: []}, allocatedprefix: 10.0.0.2/24, gateway: 10.0.0.1}
