apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /kptfile.kpt.dev
  name: kptfile.kpt.dev
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|kptfile.kpt.dev'
data:
  name: agg-layer-upf
  package-path: agg-layer-upf
