apiVersion: nf.nephio.org/v1alpha1
kind: UPFDeployment
metadata: # kpt-merge: /upf-deployment
  name: upf-deployment
  annotations:
    automation.nephio.org/config-injection: "True"
    internal.kpt.dev/upstream-identifier: 'nf.nephio.org|UPFDeployment|default|upf-deployment'
  namespace: upf
spec: {capacity: {downlinkThroughput: 10G, uplinkThroughput: 1G}, n3Interfaces: [{gatewayIPs: [10.0.0.1], ips: [10.0.0.2/24], name: n3}], n4Interfaces: [{gatewayIPs: [192.168.1.1], ips: [192.168.1.2/24], name: n4}], n6Interfaces: [{dnn: internet, interface: {gatewayIPs: [172.0.0.1], ips: [172.0.0.2/24], name: n6}, ueIPPool: 10.1.0.0/16}]}
