apiVersion: nf.nephio.org/v1alpha1
kind: UPFDeployment
metadata: # kpt-merge: /upf-deployment
  name: upf-deployment
  annotations:
    automation.nephio.org/config-injection: "True"
    internal.kpt.dev/upstream-identifier: 'nf.nephio.org|UPFDeployment|default|upf-deployment'
  namespace: upf
spec: {capacity: {downlinkThroughput: 10G, uplinkThroughput: 1G}, n3Interfaces: [{gatewayIPs: [""], ips: [""], name: n3}], n4Interfaces: [{gatewayIPs: [""], ips: [""], name: n4}], n6Interfaces: [{dnn: internet, interface: {gatewayIPs: [""], ips: [""], name: n6}, ueIPPool: ""}]}
