apiVersion: v1
kind: Service
metadata: # kpt-merge: /my-nginx-svc
  name: my-nginx-svc
  labels:
    app: nginx
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|my-nginx-svc'
  namespace: nginx-ale
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
