# fn-config.yaml
apiVersion: fn.kpt.dev/v1alpha1
kind: SetImage
metadata:
  name: nginx-config-fn
  annotations:
    config.kubernetes.io/local-config: "true"
image:
  name: nginx
  newName: bitnami/nginx
  newTag: 1.21.4
