apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  annotations:
    internal.kpt.dev/upstream-identifier: apps|Deployment|default|my-nginx
  namespace: nginx
spec:
  selector:
    matchLabels:
      app: nginx
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app: nginx
        app.kubernetes.io/name: app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - protocol: TCP
          containerPort: 80
  replicas: 2
