apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  labels:
    app: nginx
    app.kubernetes.io/name: app
  annotations:
    internal.kpt.dev/upstream-identifier: "|Service|default|my-nginx-svc"
  namespace: nginx-test
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  externalTrafficPolicy: Cluster
