# fn-config.yaml
apiVersion: fn.kpt.dev/v1alpha1
kind: SetImage
metadata:
  name: set-image
  annotations:
    config.kubernetes.io/local-config: "true"
image:
  name: bitnami/nginx
  newName: nginx
  newTag: latest
