apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: /my-nginx
  name: my-nginx
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|default|my-nginx'
  namespace: nginx-ale
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: "nginx:1.16.1"
        ports:
        - protocol: TCP
          containerPort: 80
